version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    command: mongod --auth --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Consultorio2025
      MONGODB_DATABASE: consultorio
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh mongodb://root:Consultorio2025@localhost:27017/admin --quiet"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://root:Consultorio2025@mongodb:27017/consultorio?authSource=admin
      PORT: 3001
      TZ: America/Argentina/Buenos_Aires
      CORS_ORIGINS: '*'
      GOOGLE_CALENDAR_ID: drdanielkulinka2025@gmail.com
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
    volumes:
      - ./backend/credentials.json:/app/credentials.json:ro
    expose:
      - "3001"
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - ./frontend/dist:/usr/share/nginx/html:ro
    - ./logs/nginx:/var/log/nginx
    environment:
      TZ: America/Argentina/Buenos_Aires
    networks:
      - app-network

  chatbot:
    build: 
      context: ./base-ts-baileys-memory
      dockerfile: Dockerfile
    container_name: chatbot
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://root:Consultorio2025@mongodb:27017/consultorio?authSource=admin
      PORT: 3008
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "3008:3008"
    volumes:
      - chatbot_sessions:/app/bot_sessions
      - chatbot_tmp:/app/tmp
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    networks:
      - app-network
    expose:
      - "80"
    depends_on:
      - backend
      - chatbot

networks:
  app-network:

volumes:
  mongodb_data:
  chatbot_sessions:
  chatbot_tmp:
