version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Consultorio2025
      MONGO_INITDB_DATABASE: consultorio
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  backend:
    build: ./backend
    container_name: backend    
    environment:
      - MONGODB_URI=mongodb://admin:Consultorio2025@mongo:27017/consultorio?authSource=admin
      - PORT=3001
      - TZ=America/Argentina/Buenos_Aires
      - CORS_ORIGINS=*
    expose:
      - "3001"
    depends_on:
      - mongo

  chatbot:
    build: ./base-ts-baileys-memory
    container_name: chatbot    
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:Consultorio2025@mongo:27017?authSource=admin
      - PORT=3008
      - TZ=America/Argentina/Buenos_Aires
    expose:
      - "3008"
    volumes:
      - ./data/bot_sessions:/app/bot_sessions
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    depends_on:
      - backend
      - chatbot

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - /etc/letsencrypt/live/micitamedica.me/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/micitamedica.me/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - frontend
      - backend
      - chatbot