version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Consultorio2025
      MONGO_INITDB_DATABASE: consultorio
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGO_DB_URI=mongodb://admin:Consultorio2025@mongo:27017/consultorio?authSource=admin
      - MONGO_DB_NAME=consultorio
      - PORT=3001
      - TZ=America/Argentina/Buenos_Aires
      - CORS_ORIGINS=*
      # Agrega aquí las demás variables que necesites
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  chatbot:
    build: ./base-ts-baileys-memory
    container_name: chatbot
    environment:
      - NODE_ENV=production
      - MONGO_DB_URI=mongodb://admin:Consultorio2025@mongo:27017/consultorio?authSource=admin
      - MONGO_DB_NAME=consultorio
      - PORT=3008
      - TZ=America/Argentina/Buenos_Aires
      # Agrega aquí las demás variables que necesites
    ports:
      - "3008:3008"
    depends_on:
      - mongo