version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    container_name: backend
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/consultorio
      - PORT=3001
      - TZ=America/Argentina/Buenos_Aires
      - CORS_ORIGINS=*
    expose:
      - "3001"
    depends_on:
      mongo:
        condition: service_healthy
    command: ["npm", "start"]

  chatbot:
    build: ./base-ts-baileys-memory
    container_name: chatbot
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017
      - PORT=3008
      - TZ=America/Argentina/Buenos_Aires
    expose:
      - "3008"
    volumes:
      - ./base-ts-baileys-memory/bot_sessions:/app/bot_sessions
      - ./base-ts-baileys-memory/bot_sessions/tmp:/app/tmp
    user: "1001:1001"
    depends_on:
      mongo:
        condition: service_healthy
    command: ["pnpm", "start"]

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    depends_on:
      - backend
      - chatbot

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - /etc/letsencrypt/live/micitamedica.me/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/micitamedica.me/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - frontend
      - backend
      - chatbot