version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=example
    command: ["mongod", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:example@mongo:27017/consultorio?authSource=admin
      - PORT=3001
      - TZ=America/Argentina/Buenos_Aires
      - CORS_ORIGINS=*
    expose:
      - "3001"
    depends_on:
      mongo:
        condition: service_healthy
    command: sh -c "sleep 10 && npm start"

  chatbot:
    build: ./base-ts-baileys-memory
    container_name: chatbot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:example@mongo:27017?authSource=admin
      - PORT=3008
      - TZ=America/Argentina/Buenos_Aires
    expose:
      - "3008"
    volumes:
      - ./base-ts-baileys-memory/bot_sessions:/app/bot_sessions
      - ./base-ts-baileys-memory/bot_sessions/tmp:/app/tmp
    user: "1001:1001"
    depends_on:
      mongo:
        condition: service_healthy
    command: sh -c "sleep 15 && pnpm start"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - backend
      - chatbot

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - /etc/letsencrypt/live/micitamedica.me/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/micitamedica.me/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - frontend
      - backend
      - chatbot